services:
  postgres:
    image: postgres:16
    container_name: agendamento_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: agendamento_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pucminasagendamento
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agendamento_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
